name: Publish

on:
  push:
    branches:
      - "root"
      - "fork"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    env:
      ORG_GRADLE_PROJECT_signingKey: "${{ secrets.SIGNING_KEY }}"
      ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.SIGNING_KEY_PASSWORD }}"

      OSSRH_PASSWORD: "${{ secrets.GCP_ACCOUNT_KEY }}"
      TOKEN: "${{ secrets.TOKEN }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 17
          distribution: temurin

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Get version
        id: project-version

        run: |
          VERSION=$(kotlin .github/get-version.main.kts)

          echo "Project version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Gradle properties

        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties
          echo -e "\norg.gradle.jvmargs=-XX:MaxMetaspaceSize=5G" >> ~/.gradle/gradle.properties

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v4

        with:
          dependency-graph: generate-and-submit


      - name: Gradle (Publish)
        run: "./gradlew publish"

        if: contains(steps.project-version.outputs.version, '-SNAPSHOT')
